### PR TITLE
Retry requests

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

**Comment by Nothing4You** [comment]
Is there a possibility to get some logging from this (retries) easily?

I just ran it again and got timeouts for lemmy.world again, which suggests that lemmy.world would have failed 3 times in a row with 100 concurrency on my Hetzner VPS.

When I find some more time later or tomorrow I'll do a run and capture packets to try if I can see more there in a pcap.

**Comment by Nothing4You** [comment]
At least for lemmy.world, it seems that these issues are not related to this crawler.
I just ran a curl from the same VPS that took nearly 30s until I got a response.
I also ran a curl from my local machine that took about 7s.
Afterwards I was able to get several requests through at ~1s for some time.

**Comment by Nothing4You** [comment]
What do you think about exposing the timeout as cli arg?

**Comment by Nutomic** [comment]
Good idea! Ive added `--timeout` and increased the default timeout to 10s.

**Review by dessalines — APPROVED** [review]

**Comment by Nothing4You** [comment]
thanks, just had a chance to try with increased timeout and at least based on the instance count in the result it seems to be more reliable when i just tested this with 60s timeout, yielding a total of 868 instances on 100 concurrency right now.

**Pull request merged**
