### PR TITLE
Add regex to check that domains are valid

### PR DESCRIPTION
**Pull request by Nutomic**
It currently outputs `!technology@beehaw.org` as a Lemmy instance. Need to check that its actually a valid domain.

### CODE REVIEW

**Comment by Nutomic** [comment]
How do you mean?

**Comment by dessalines** [comment]
Maybe something like making sure it doesn't have a path: https://docs.rs/url/latest/url/struct.Url.html#method.path

**Comment by dessalines** [comment]
Maybe something like making sure it doesn't have a path: https://docs.rs/url/latest/url/struct.Url.html#method.path

**Comment by Nutomic** [comment]
Good idea but the code would be very awkward. I will leave it like this.

**Pull request merged**
